import type { Locale } from '../i18n/types';
const en = { defaultSubagentModel: 'Default subagent model', defaultSubagentHint: 'Used for newly spawned subagents in all Kimi sessions.', children: 'Child conversations', childHint: 'Independent conversations linked to this parent. Open a child to send instructions.', tasks: 'Subagents in this conversation', taskHint: 'These agents share this conversation; they are not separate conversations.', title: 'Child conversation title', create: 'Create child', open: 'Open', configure: 'Settings', stop: 'Stop', refresh: 'Refresh', empty: 'None yet', loading: 'Loading…', model: 'Model', thinking: 'Thinking effort', permission: 'Permission', save: 'Save settings', saved: 'Settings saved', manual: 'Ask for approval', auto: 'Automatic approval', yolo: 'Allow all', default: 'Default' };
type Copy = { readonly [K in keyof typeof en]: string };
const zh: Copy = { defaultSubagentModel: '子智能体默认模型', defaultSubagentHint: '新启动的子智能体将默认使用此模型。', children: '子会话', childHint: '与当前会话关联的独立会话，打开后可发送任务。', tasks: '当前会话内的子智能体', taskHint: '这些智能体在当前会话内运行，不是独立会话。', title: '子会话标题', create: '创建子会话', open: '打开', configure: '设置', stop: '停止', refresh: '刷新', empty: '暂无', loading: '正在加载…', model: '模型', thinking: '思考强度', permission: '权限', save: '保存设置', saved: '设置已保存', manual: '请求审批', auto: '自动审批', yolo: '全部允许', default: '默认' };
export const kimiWebAgentsUi: Readonly<Record<Locale, Copy>> = {
 en, 'zh-CN': zh,
 'zh-TW': { ...zh, children: '子對話', childHint: '與目前對話關聯的獨立對話，開啟後可傳送任務。', tasks: '目前對話內的子智慧體', taskHint: '這些智慧體在目前對話內執行，不是獨立對話。', title: '子對話標題', create: '建立子對話', open: '開啟', configure: '設定', refresh: '重新整理', empty: '暫無', loading: '正在載入…', permission: '權限', save: '儲存設定', saved: '設定已儲存', manual: '請求審批', auto: '自動審批', yolo: '全部允許', default: '預設' },
 ja: { defaultSubagentModel: 'サブエージェントの既定モデル', defaultSubagentHint: '新しいサブエージェントに適用されます。', children: '子会話', childHint: '親に関連する独立した会話です。開いて指示を送信します。', tasks: 'この会話のサブエージェント', taskHint: '同じ会話で動作し、独立した会話ではありません。', title: '子会話のタイトル', create: '子会話を作成', open: '開く', configure: '設定', stop: '停止', refresh: '更新', empty: 'まだありません', loading: '読込中…', model: 'モデル', thinking: '思考強度', permission: '権限', save: '設定を保存', saved: '保存しました', manual: '承認を要求', auto: '自動承認', yolo: 'すべて許可', default: '既定' },
 eo: { defaultSubagentModel: 'Defaŭlta subagenta modelo', defaultSubagentHint: 'Uzata por novaj subagentoj.', children: 'Infanaj konversacioj', childHint: 'Sendependaj konversacioj ligitaj al ĉi tiu gepatro. Malfermu por sendi instrukciojn.', tasks: 'Subagentoj en ĉi tiu konversacio', taskHint: 'Ĉi tiuj agentoj dividas ĉi tiun konversacion; ili ne estas apartaj konversacioj.', title: 'Titolo de infana konversacio', create: 'Krei infanon', open: 'Malfermi', configure: 'Agordoj', stop: 'Haltigi', refresh: 'Refreŝigi', empty: 'Ankoraŭ neniu', loading: 'Ŝargante…', model: 'Modelo', thinking: 'Pensa intenseco', permission: 'Permeso', save: 'Konservi agordojn', saved: 'Agordoj konservitaj', manual: 'Peti aprobon', auto: 'Aŭtomata aprobo', yolo: 'Permesi ĉion', default: 'Defaŭlta' },
};
